angular.module("Love").constant("config", {
	url: "http://www.henduoniu.com",
	imageUrl: "http://www.henduoniu.com/files/image?name=",
	request: {
		"SUCCESS": "200",
		"TOKEN_INVALID": "405"
	},
	response: {
		"SUCCESS": 1
	},
	common_params: {
		invoke: "h5",
		app_sign: "123456"
	},
	weixin: {
		"base_url": "https://open.weixin.qq.com/connect/oauth2/authorize",
		"access_token_url": "https://api.weixin.qq.com/sns/oauth2/access_token",
		"userinfo_url": "https://api.weixin.qq.com/sns/userinfo",
		"appid": "wx24cc097bb3db1ce3",
		"secret": "b029f342a2e50a9a081a3d450424e71f",
		"redirect_uri": "http://www.henduoniu.com/oauth",
		"payment_redirect_uri": "http://www.henduoniu.com/mobile/#/payment",
		"response_type": "code",
		"silence_scope": "snsapi_base",
		"scope": "snsapi_userinfo",
		"state": "weixin",
		"wechat_redirect": "#wechat_redirect",
	},
	share: {},
	interceptor: [
		"account",
		"appointment",
		"appointment1",
		"appointment2",
		"authen",
		"basic",
		"chat",
		"create_appointment",
		"index",
		"lovers",
		"manual_authen",
		"mating",
		"member",
		"member1",
		"member2",
		"messages",
		"message",
		"mylove",
		"phone_authen",
		"realname_authen",
		"payment",
		"search",
		"services",
		"signin",
		"signup",
		"single",
		"search_conditional",
		"send_messages",
		"oauth",
		"appointment1_refuse",
		"appointment1_sure",
		"appointment2_refuse",
		"appointment2_sure",
		"detail",
		"charge",
		"me",
		"ta",
		"tags",
		"withdrawals",
		"recommendation",
		"visitors",
		"show",
	]
});